<?xml version="1.0"?>
<project name="buildSystem" default="deploy">
	<property file="build.properties"/>
	<property environment="env"/>
	<property name="scratchorg.alias" value="NFLPoolScratchOrg"/>

	<condition property="sf.command" value="sf.cmd">
		<os family="windows"/>
	</condition>
	<property name="sf.command" value="sf"/>

	<import file="ant/deploy.xml"/>
</project>
