SOBJECT="Game__c"
QUERY_FIELDS="Id, Week__c, Start_Time__c, Spread__c, Home_Score__c, Visiting_Score__c, Final__c, Home_Team__c, Visiting_Team__c"
QUERY_ORDER="ORDER BY Week__c, Start_Time__c"
CSV_HEADER="External_ID__c,Week__c,Start_Time__c,Spread__c,Home_Score__c,Visiting_Score__c,Final__c,Home_Team__r.External_ID__c,Visiting_Team__r.External_ID__c"
EXTERNAL_ID_FIELD="External_ID__c"
