public class Constants {
	public static final String PLAYER_PROFILE = 'Player';
	public static final String PLAYER_PLATFORM_PROFILE = 'Player - Platform';
	public static final String POOL_ADMIN_PROFILE = 'Pool Administrator';
	public static final String SYSTEM_ADMIN_PROFILE = 'System Administrator';

	public static final String NFL_POOL_CHATTER_GROUP = 'NFL Pool';
	public static final String NFL_POOL_ADMINS_CHATTER_GROUP = 'NFL Pool Administrators';
}